// Extended personality data for the profile template page

export const cognitiveFunctions = {
  INTJ: { dominant: "Ni — Introverted Intuition", auxiliary: "Te — Extraverted Thinking", tertiary: "Fi — Introverted Feeling", inferior: "Se — Extraverted Sensing" },
  INTP: { dominant: "Ti — Introverted Thinking", auxiliary: "Ne — Extraverted Intuition", tertiary: "Si — Introverted Sensing", inferior: "Fe — Extraverted Feeling" },
  ENTJ: { dominant: "Te — Extraverted Thinking", auxiliary: "Ni — Introverted Intuition", tertiary: "Se — Extraverted Sensing", inferior: "Fi — Introverted Feeling" },
  ENTP: { dominant: "Ne — Extraverted Intuition", auxiliary: "Ti — Introverted Thinking", tertiary: "Fe — Extraverted Feeling", inferior: "Si — Introverted Sensing" },
  INFJ: { dominant: "Ni — Introverted Intuition", auxiliary: "Fe — Extraverted Feeling", tertiary: "Ti — Introverted Thinking", inferior: "Se — Extraverted Sensing" },
  INFP: { dominant: "Fi — Introverted Feeling", auxiliary: "Ne — Extraverted Intuition", tertiary: "Si — Introverted Sensing", inferior: "Te — Extraverted Thinking" },
  ENFJ: { dominant: "Fe — Extraverted Feeling", auxiliary: "Ni — Introverted Intuition", tertiary: "Se — Extraverted Sensing", inferior: "Ti — Introverted Thinking" },
  ENFP: { dominant: "Ne — Extraverted Intuition", auxiliary: "Fi — Introverted Feeling", tertiary: "Te — Extraverted Thinking", inferior: "Si — Introverted Sensing" },
  ISTJ: { dominant: "Si — Introverted Sensing", auxiliary: "Te — Extraverted Thinking", tertiary: "Fi — Introverted Feeling", inferior: "Ne — Extraverted Intuition" },
  ISFJ: { dominant: "Si — Introverted Sensing", auxiliary: "Fe — Extraverted Feeling", tertiary: "Ti — Introverted Thinking", inferior: "Ne — Extraverted Intuition" },
  ESTJ: { dominant: "Te — Extraverted Thinking", auxiliary: "Si — Introverted Sensing", tertiary: "Ne — Extraverted Intuition", inferior: "Fi — Introverted Feeling" },
  ESFJ: { dominant: "Fe — Extraverted Feeling", auxiliary: "Si — Introverted Sensing", tertiary: "Ne — Extraverted Intuition", inferior: "Ti — Introverted Thinking" },
  ISTP: { dominant: "Ti — Introverted Thinking", auxiliary: "Se — Extraverted Sensing", tertiary: "Ni — Introverted Intuition", inferior: "Fe — Extraverted Feeling" },
  ISFP: { dominant: "Fi — Introverted Feeling", auxiliary: "Se — Extraverted Sensing", tertiary: "Ni — Introverted Intuition", inferior: "Te — Extraverted Thinking" },
  ESTP: { dominant: "Se — Extraverted Sensing", auxiliary: "Ti — Introverted Thinking", tertiary: "Fe — Extraverted Feeling", inferior: "Ni — Introverted Intuition" },
  ESFP: { dominant: "Se — Extraverted Sensing", auxiliary: "Fi — Introverted Feeling", tertiary: "Te — Extraverted Thinking", inferior: "Ni — Introverted Intuition" },
};

export const traitScores = {
  INTJ: { creativity: 80, empathy: 40, leadership: 85, structure: 90, spontaneity: 25, sociability: 30 },
  INTP: { creativity: 90, empathy: 45, leadership: 55, structure: 50, spontaneity: 55, sociability: 25 },
  ENTJ: { creativity: 70, empathy: 40, leadership: 95, structure: 90, spontaneity: 40, sociability: 75 },
  ENTP: { creativity: 92, empathy: 50, leadership: 75, structure: 35, spontaneity: 80, sociability: 70 },
  INFJ: { creativity: 85, empathy: 90, leadership: 65, structure: 70, spontaneity: 35, sociability: 40 },
  INFP: { creativity: 90, empathy: 92, leadership: 40, structure: 35, spontaneity: 60, sociability: 35 },
  ENFJ: { creativity: 72, empathy: 90, leadership: 88, structure: 65, spontaneity: 50, sociability: 85 },
  ENFP: { creativity: 88, empathy: 82, leadership: 65, structure: 30, spontaneity: 88, sociability: 88 },
  ISTJ: { creativity: 40, empathy: 50, leadership: 70, structure: 95, spontaneity: 15, sociability: 35 },
  ISFJ: { creativity: 50, empathy: 88, leadership: 50, structure: 85, spontaneity: 20, sociability: 50 },
  ESTJ: { creativity: 45, empathy: 45, leadership: 90, structure: 95, spontaneity: 20, sociability: 65 },
  ESFJ: { creativity: 55, empathy: 85, leadership: 70, structure: 80, spontaneity: 35, sociability: 88 },
  ISTP: { creativity: 75, empathy: 40, leadership: 50, structure: 55, spontaneity: 70, sociability: 30 },
  ISFP: { creativity: 82, empathy: 75, leadership: 35, structure: 35, spontaneity: 78, sociability: 45 },
  ESTP: { creativity: 70, empathy: 45, leadership: 72, structure: 35, spontaneity: 90, sociability: 80 },
  ESFP: { creativity: 65, empathy: 78, leadership: 55, structure: 25, spontaneity: 92, sociability: 92 },
};

export const compatibility = {
  INTJ: { best: ["ENTP", "ENFP"], good: ["INTJ", "INTP", "ENTJ", "INFJ"], challenging: ["ESFP", "ISFP"] },
  INTP: { best: ["ENTJ", "ENFJ"], good: ["INTP", "INTJ", "ENTP", "INFJ"], challenging: ["ESFJ", "ISFJ"] },
  ENTJ: { best: ["INTP", "INFP"], good: ["ENTJ", "ENTP", "INTJ", "ENFJ"], challenging: ["ISFP", "ESFP"] },
  ENTP: { best: ["INTJ", "INFJ"], good: ["ENTP", "ENTJ", "INTP", "ENFP"], challenging: ["ISTJ", "ISFJ"] },
  INFJ: { best: ["ENTP", "ENFP"], good: ["INFJ", "INTJ", "INFP", "ENFJ"], challenging: ["ESTP", "ESFP"] },
  INFP: { best: ["ENTJ", "ENFJ"], good: ["INFP", "INFJ", "ENFP", "INTP"], challenging: ["ESTJ", "ESFJ"] },
  ENFJ: { best: ["INTP", "INFP"], good: ["ENFJ", "ENFP", "INFJ", "ENTJ"], challenging: ["ISTP", "ESTP"] },
  ENFP: { best: ["INTJ", "INFJ"], good: ["ENFP", "ENFJ", "INFP", "ENTP"], challenging: ["ISTJ", "ESTJ"] },
  ISTJ: { best: ["ESFP", "ESTP"], good: ["ISTJ", "ISFJ", "ESTJ", "ISTP"], challenging: ["ENFP", "ENTP"] },
  ISFJ: { best: ["ESTP", "ESFP"], good: ["ISFJ", "ISTJ", "ESFJ", "ISFP"], challenging: ["ENTP", "ENFP"] },
  ESTJ: { best: ["ISFP", "INFP"], good: ["ESTJ", "ESFJ", "ISTJ", "ESTP"], challenging: ["INFP", "ENFP"] },
  ESFJ: { best: ["ISFP", "INFP"], good: ["ESFJ", "ESTJ", "ISFJ", "ENFJ"], challenging: ["INTP", "ISTP"] },
  ISTP: { best: ["ESFJ", "ESTJ"], good: ["ISTP", "ISTJ", "ESTP", "ISFP"], challenging: ["ENFJ", "INFJ"] },
  ISFP: { best: ["ESTJ", "ESFJ"], good: ["ISFP", "ISFJ", "ESFP", "ISTP"], challenging: ["ENTJ", "ESTJ"] },
  ESTP: { best: ["ISFJ", "ISTJ"], good: ["ESTP", "ESFP", "ISTP", "ESTJ"], challenging: ["INFJ", "ENFJ"] },
  ESFP: { best: ["ISTJ", "ISFJ"], good: ["ESFP", "ESTP", "ISFP", "ESFJ"], challenging: ["INTJ", "INFJ"] },
};

export const workStyle = {
  INTJ: { environment: "Autonomous and intellectually stimulating", motivation: "Mastery, competence, and long-term vision", conflict: "Avoids emotional conflict; prefers logic-based resolution", leadership: "Strategic visionary who delegates efficiently" },
  INTP: { environment: "Freedom to explore ideas without rigid structure", motivation: "Intellectual puzzles and theoretical discovery", conflict: "Avoids conflict; prefers rational debate over emotional discussion", leadership: "Leads through expertise and innovative thinking" },
  ENTJ: { environment: "Fast-paced with clear goals and authority", motivation: "Achievement, power, and organizational excellence", conflict: "Direct and decisive; confronts issues head-on", leadership: "Commands respect through decisive action and vision" },
  ENTP: { environment: "Dynamic, creative with room for experimentation", motivation: "Novel challenges and intellectual debate", conflict: "Debates openly; can enjoy a good argument", leadership: "Inspires through ideas and energetic engagement" },
  INFJ: { environment: "Purposeful, harmonious, and values-driven", motivation: "Meaningful work that helps others grow", conflict: "Avoids conflict but will assert values firmly when needed", leadership: "Leads through inspiration and empathic guidance" },
  INFP: { environment: "Creative and autonomous with personal meaning", motivation: "Alignment with personal values and helping others", conflict: "Avoids conflict; deeply affected by workplace disharmony", leadership: "Leads by example and passionate advocacy" },
  ENFJ: { environment: "Collaborative and people-focused", motivation: "Developing others and achieving shared goals", conflict: "Mediates and seeks harmony; dislikes personal attacks", leadership: "Charismatic coach who brings out the best in people" },
  ENFP: { environment: "Creative, energetic, and socially rich", motivation: "Inspiration, connection, and new possibilities", conflict: "Uses charm and empathy; may avoid hard truths", leadership: "Motivational and visionary, rallies people around ideas" },
  ISTJ: { environment: "Structured, stable, and process-driven", motivation: "Duty, reliability, and completing tasks correctly", conflict: "Reserved; addresses conflict through established rules", leadership: "Steady, reliable manager who enforces high standards" },
  ISFJ: { environment: "Supportive, caring, and organized", motivation: "Helping others and maintaining harmony", conflict: "Avoids conflict; may internalize issues rather than voice them", leadership: "Quiet leader who earns trust through consistent care" },
  ESTJ: { environment: "Organized, goal-oriented, and hierarchical", motivation: "Order, efficiency, and tangible results", conflict: "Direct and blunt; enforces rules and expectations", leadership: "Traditional manager who excels at execution and accountability" },
  ESFJ: { environment: "Warm, social, and team-oriented", motivation: "Belonging, appreciation, and helping others succeed", conflict: "Wants consensus; upset by personal discord", leadership: "Supportive team-builder who prioritizes morale" },
  ISTP: { environment: "Hands-on, practical, and autonomous", motivation: "Efficiency, craftsmanship, and problem-solving in action", conflict: "Disengages from emotional conflict; prefers practical solutions", leadership: "Leads by competence; modest but highly capable" },
  ISFP: { environment: "Creative, flexible, and low-pressure", motivation: "Aesthetic expression and personal authenticity", conflict: "Avoids conflict; may withdraw when values are challenged", leadership: "Leads quietly through action and genuine care" },
  ESTP: { environment: "Fast-moving, action-oriented, and social", motivation: "Immediate results, excitement, and tangible wins", conflict: "Direct and no-nonsense; solves it fast and moves on", leadership: "Bold, decisive leader who thrives in crisis situations" },
  ESFP: { environment: "Fun, energetic, and people-filled", motivation: "Enjoyment, connection, and real-world impact", conflict: "Avoids tension; uses humor and warmth to defuse", leadership: "Engaging, enthusiastic leader who boosts morale" },
};

export const strengthDetails = {
  INTJ: [
    { title: "Masterful Strategic Thinking", desc: "INTJs can see far into the future and architect plans that others miss entirely. They connect dots across disciplines and anticipate obstacles before they arise." },
    { title: "Fierce Independence", desc: "They do not need validation from others to pursue their goals. This independence allows them to make bold decisions without being paralyzed by social consensus." },
    { title: "High Standards & Determination", desc: "Once an INTJ commits to a goal, they pursue it with relentless drive. Their perfectionism isn't vanity — it's a genuine desire for excellence." },
    { title: "Innovative Problem Solving", desc: "INTJs naturally reframe problems and discard conventional wisdom when it no longer serves. They love finding the most elegant, efficient solution." },
  ],
  INTP: [
    { title: "Deep Analytical Mind", desc: "INTPs can deconstruct complex systems with ease, finding the logical core of any argument. They are natural theorists who love precision." },
    { title: "Relentless Curiosity", desc: "They follow ideas wherever they lead, often mastering multiple fields. Their thirst for understanding is genuinely insatiable." },
    { title: "Intellectual Honesty", desc: "INTPs hold their own ideas to the same scrutiny they apply to others. They will readily change their mind when faced with better evidence." },
    { title: "Creative & Original", desc: "By combining ideas from different domains in unexpected ways, INTPs regularly arrive at genuinely novel insights and inventions." },
  ],
  ENTJ: [
    { title: "Visionary Leadership", desc: "ENTJs see the big picture and are extraordinarily skilled at mobilizing people and resources toward a long-term vision." },
    { title: "Decisive Under Pressure", desc: "Where others hesitate, ENTJs act. They gather data quickly, decide confidently, and course-correct without ego attachment." },
    { title: "Strategic Efficiency", desc: "They have a rare ability to see waste in any system and restructure it for maximum output. They are born optimizers." },
    { title: "High Confidence", desc: "ENTJs project authority naturally. This self-assurance inspires confidence in teams and makes them compelling in negotiations." },
  ],
  ENTP: [
    { title: "Rapid Creative Thinking", desc: "ENTPs make connections at lightning speed across distant domains, generating ideas that surprise even themselves." },
    { title: "Persuasive Communicator", desc: "They can argue any position convincingly and understand opposing views deeply — making them exceptional debaters and advocates." },
    { title: "Energetic & Inspiring", desc: "Their enthusiasm for ideas is genuinely contagious. They make brainstorming sessions feel electric and alive." },
    { title: "Adaptable Strategist", desc: "ENTPs thrive on change and rarely get locked into a failing approach. They pivot quickly and find new angles instinctively." },
  ],
  INFJ: [
    { title: "Deep Empathic Insight", desc: "INFJs understand people at a level that feels almost supernatural. They pick up on unspoken needs and hidden motivations effortlessly." },
    { title: "Long-Range Vision", desc: "Driven by their dominant Ni, INFJs can sense where things are heading and plan accordingly — often years before others catch on." },
    { title: "Principled Integrity", desc: "INFJs do not bend their values under social pressure. They'd rather walk away from an opportunity than compromise who they are." },
    { title: "Inspiring Depth", desc: "When an INFJ speaks about something they care about, it resonates. Their authenticity and depth make them deeply compelling." },
  ],
  INFP: [
    { title: "Profound Empathy", desc: "INFPs feel with others so deeply that they can understand experiences far removed from their own. This makes them gifted healers and storytellers." },
    { title: "Authentic Creativity", desc: "Everything an INFP creates comes from a genuine inner place. Their art, writing, and ideas carry emotional truth that outlasts trends." },
    { title: "Values-Driven Integrity", desc: "INFPs will not be bought or bullied away from what they believe is right. This quiet moral courage is one of their greatest gifts." },
    { title: "Open-Minded & Curious", desc: "They approach new people and ideas with genuine openness, making space for others to be exactly who they are without judgment." },
  ],
  ENFJ: [
    { title: "Magnetic Charisma", desc: "ENFJs have a gift for making everyone feel seen and important. Their warmth is genuine and draws people in effortlessly." },
    { title: "Natural Mentor", desc: "They see potential in others before those people see it themselves, and they know exactly how to encourage it forward." },
    { title: "Strategic Empathy", desc: "ENFJs combine emotional intelligence with big-picture thinking — they build teams that are both high-performing and deeply motivated." },
    { title: "Reliable & Principled", desc: "When an ENFJ commits to something — a person, a project, a cause — they follow through completely and with full heart." },
  ],
  ENFP: [
    { title: "Boundless Enthusiasm", desc: "ENFPs bring infectious energy to everything they touch. They have a rare ability to make ordinary things feel exciting." },
    { title: "Deeply Human Connection", desc: "They genuinely care about the people they meet and form authentic connections with remarkable speed and depth." },
    { title: "Creative Versatility", desc: "ENFPs can generate ideas in almost any domain and adapt their style to what the moment needs. They are creative chameleons." },
    { title: "Courageous Authenticity", desc: "They live on their own terms and are willing to be different, weird, or vulnerable — and that bravery inspires others to do the same." },
  ],
  ISTJ: [
    { title: "Bedrock Reliability", desc: "If an ISTJ says they will do something, it gets done — on time and to a high standard. This dependability is extremely rare and precious." },
    { title: "Exceptional Memory for Detail", desc: "They store experience methodically and draw on past lessons with uncanny precision, making them excellent historians of their own field." },
    { title: "Calm Under Pressure", desc: "ISTJs don't panic. When chaos erupts, they anchor themselves in process and procedure, providing stability for those around them." },
    { title: "Deep Sense of Duty", desc: "They take responsibility seriously and will not cut corners even when no one is watching. Their integrity is structural, not performed." },
  ],
  ISFJ: [
    { title: "Selfless Care", desc: "ISFJs notice when others are struggling and respond with practical warmth, often before anyone asks. They are the quiet pillars of every community." },
    { title: "Meticulous Attention to Detail", desc: "They remember what matters to others — preferences, histories, needs — and use that knowledge to provide support that feels personal." },
    { title: "Steady & Trustworthy", desc: "ISFJs provide the kind of consistency and loyalty that forms the foundation of lasting relationships and reliable institutions." },
    { title: "Humble Competence", desc: "They rarely seek credit, preferring to let the quality of their work speak for itself. This quiet excellence earns deep respect." },
  ],
  ESTJ: [
    { title: "Commanding Organizational Skill", desc: "ESTJs can take a chaotic situation and impose clear, functional structure on it with impressive speed. They make systems that actually work." },
    { title: "Decisive Authority", desc: "They are not afraid to make the hard call and own the result. This decisiveness provides clarity that teams desperately need." },
    { title: "Consistent & Fair", desc: "ESTJs apply the same rules to everyone, including themselves. This consistency earns the respect of those who work with them." },
    { title: "Strong Work Ethic", desc: "They lead by example and put in the hours required. An ESTJ does not ask anyone to do what they wouldn't do themselves." },
  ],
  ESFJ: [
    { title: "Deeply Caring Presence", desc: "ESFJs make the people around them feel genuinely valued and supported. Their warmth is practical — they show up, not just care." },
    { title: "Social Intelligence", desc: "They read group dynamics with exceptional accuracy and know how to bring harmony to diverse teams and social settings." },
    { title: "Organized & Reliable", desc: "ESFJs combine warmth with real competence. They plan, follow through, and remember the small things that make a big difference." },
    { title: "Community Builder", desc: "They create belonging wherever they go — in families, workplaces, and communities. Their networks are built on genuine reciprocity." },
  ],
  ISTP: [
    { title: "Masterful Hands-On Problem Solving", desc: "ISTPs excel at diagnosing and fixing real-world problems in the moment, with minimal fuss and maximal efficiency." },
    { title: "Cool Detachment Under Pressure", desc: "Their calm in crisis is legendary. ISTPs assess situations without panic and act with economy and precision." },
    { title: "Technical Excellence", desc: "They develop genuine mastery in their chosen craft, understanding systems at a mechanical level few can match." },
    { title: "Radical Self-Sufficiency", desc: "ISTPs don't wait to be rescued. They figure things out, build what they need, and solve what they encounter." },
  ],
  ISFP: [
    { title: "Genuine Aesthetic Sensibility", desc: "ISFPs see beauty in ways others miss and express it through art, music, design, or simply the way they curate their world." },
    { title: "Deep Emotional Authenticity", desc: "They live and feel deeply, and when they express themselves, it carries the full weight of genuine experience." },
    { title: "Present-Moment Awareness", desc: "ISFPs are fully alive in the now — experiencing the sensory world with richness and gratitude that others overlook." },
    { title: "Quietly Compassionate", desc: "They notice suffering and respond with gentle, practical care. Their kindness is never showy, but it is always felt." },
  ],
  ESTP: [
    { title: "Masterful Crisis Response", desc: "ESTPs think and act at the speed of events. In emergencies, they are the ones who step forward while others freeze." },
    { title: "Persuasive & Charismatic", desc: "Their directness and confidence make them natural salespeople, negotiators, and performers who capture attention in any room." },
    { title: "Sharp Situational Awareness", desc: "They read rooms, people, and dynamics in real time with remarkable accuracy, adapting their approach on the fly." },
    { title: "Fearless Risk Tolerance", desc: "ESTPs push boundaries and try things others consider too risky — and this boldness often pays off in ways the cautious never experience." },
  ],
  ESFP: [
    { title: "Irresistible Warmth", desc: "ESFPs light up any room they enter. Their joy is genuine and their enthusiasm for people and life is wonderfully contagious." },
    { title: "Exceptional Performer", desc: "Whether on a stage or in a conversation, ESFPs thrive in the spotlight and know instinctively how to read and engage an audience." },
    { title: "Bold Practical Creativity", desc: "They create beautiful, joyful experiences in the real world — events, spaces, moments — that others treasure for years." },
    { title: "Spontaneous Generosity", desc: "ESFPs give freely — their time, energy, attention, and resources — because sharing makes life better for everyone." },
  ],
};

export const recommendations = {
  INTJ: [
    { emoji: "🎯", title: "Set 10-year goals", desc: "Your Ni thrives when given a long horizon. Write down where you want to be in a decade — be specific and ruthless." },
    { emoji: "🤝", title: "Practice emotional vulnerability", desc: "Your inferior Fe craves connection. Share something personal with someone you trust at least once a week." },
    { emoji: "📚", title: "Read across disciplines", desc: "INTJs do their best thinking at the intersection of fields. Pick up a book outside your expertise this month." },
    { emoji: "🧘", title: "Schedule true downtime", desc: "Your mind rarely stops. Protect time for rest — not productivity. Your Se needs sensory experience, not just ideas." },
    { emoji: "💬", title: "Ask before advising", desc: "When someone shares a problem, ask 'Do you want advice or just to be heard?' Your instinct to solve can sometimes feel cold." },
    { emoji: "🌱", title: "Embrace imperfect action", desc: "Your perfectionism can cause paralysis. Ship something 90% done. Done beats perfect every time." },
  ],
  INTP: [
    { emoji: "⏰", title: "Use time-boxing", desc: "Analysis paralysis is your nemesis. Set a timer — when it rings, make the decision with what you have." },
    { emoji: "🗣️", title: "Share your half-formed ideas", desc: "You wait until ideas are 'ready.' They never are. Talking through incomplete thoughts accelerates your thinking." },
    { emoji: "🏋️", title: "Ground yourself physically", desc: "Your Se is inferior — exercise, cook a meal, go for a walk. Physical activity quiets your overthinking mind." },
    { emoji: "📅", title: "Build simple routines", desc: "Your tertiary Si benefits from anchor habits: same wake time, same morning ritual. It frees mental RAM for ideas." },
    { emoji: "💞", title: "Check in emotionally", desc: "Ask people you care about how they're feeling — and listen without trying to fix. Relationships need watering." },
    { emoji: "🚀", title: "Launch before it's perfect", desc: "Your best theoretical framework means nothing unless it's tested in reality. Ship something and iterate." },
  ],
  ENTJ: [
    { emoji: "👂", title: "Listen to understand, not respond", desc: "Your Te rushes to solution. Slow down — the person speaking often knows more than you think. Wait for the full picture." },
    { emoji: "💓", title: "Check your emotional impact", desc: "Your directness is an asset, but ask yourself: 'Did I leave them feeling better or just corrected?' Both can be true." },
    { emoji: "🎭", title: "Embrace play and humor", desc: "Your inferior Fi needs lightness. Not every interaction needs to be productive. Let yourself enjoy people for fun." },
    { emoji: "🛑", title: "Build in strategic pauses", desc: "Before executing, sit with uncertainty a moment. INTJs call this 'marinating.' ENTJs need it too." },
    { emoji: "🌿", title: "Delegate meaningfully", desc: "Don't just assign tasks — assign ownership. People do their best work when they feel genuinely trusted." },
    { emoji: "📖", title: "Study philosophy", desc: "Your tertiary Se experiences the world; studying wisdom traditions helps your Fi develop values beyond goals." },
  ],
  ENTP: [
    { emoji: "🏁", title: "Finish what you start", desc: "Pick one project and see it to completion before starting another. The gap between your ideas and execution is the work." },
    { emoji: "🎙️", title: "Argue for the other side", desc: "You're persuasive — practice steelmanning positions you disagree with. It sharpens thinking and builds empathy." },
    { emoji: "🤫", title: "Listen without countering", desc: "Practice letting someone finish their entire thought before you respond. Count to three before speaking." },
    { emoji: "📋", title: "Create simple systems", desc: "Your inferior Si rebels against routine. Build just enough structure to support your big ideas without feeling caged." },
    { emoji: "🌊", title: "Sit with discomfort", desc: "When boredom hits, resist the urge to chase novelty. The ideas that matter most often require sustained attention." },
    { emoji: "💝", title: "Express appreciation directly", desc: "Tell people you care about them explicitly. Your wit and intelligence are gifts — so is warmth. Use it." },
  ],
  INFJ: [
    { emoji: "🛡️", title: "Protect your energy", desc: "You absorb others' emotions. Learn to recognize when you're carrying someone else's feelings as your own." },
    { emoji: "✍️", title: "Journal daily", desc: "Your Ni works best when given a space to unspool its visions. Writing unlocks insights your conscious mind can't access." },
    { emoji: "🌿", title: "Rest before you're depleted", desc: "You give until empty. Schedule recovery time before you feel you need it — not after you've crashed." },
    { emoji: "🗣️", title: "Share your opinions earlier", desc: "You often wait until you're certain. But your half-formed insight is worth more than most people's finished thought." },
    { emoji: "🎨", title: "Create something without purpose", desc: "Not everything you make needs to help someone. Create for the sheer pleasure of expression. Your Fe will thank you." },
    { emoji: "🤝", title: "Let people help you", desc: "You give readily but struggle to receive. Letting others support you is an act of connection, not weakness." },
  ],
  INFP: [
    { emoji: "🗺️", title: "Make your values concrete", desc: "Translate your ideals into one specific action this week. Idealism without action becomes grief. One step counts." },
    { emoji: "📝", title: "Write or create daily", desc: "Even five minutes. Your Ne+Fi generates a constant stream of insight — give it somewhere to go." },
    { emoji: "🌐", title: "Connect with a cause", desc: "Find a community that shares your values. INFPs flourish when their gifts serve something larger than themselves." },
    { emoji: "⚙️", title: "Build one reliable system", desc: "A simple calendar, a weekly review — just one structure to support your gifts without feeling bureaucratic." },
    { emoji: "🌅", title: "Tolerate unresolved tension", desc: "Not everything can be made beautiful or fair. Practice sitting with ambiguity without needing to fix it immediately." },
    { emoji: "💬", title: "Speak up about your needs", desc: "You are skilled at understanding others' needs. Practice naming your own, out loud, to people who care about you." },
  ],
  ENFJ: [
    { emoji: "🪞", title: "Check your own needs first", desc: "You give oxygen to everyone else before putting on your own mask. What do YOU need right now? Start there." },
    { emoji: "🚫", title: "Practice saying no", desc: "Your desire to help can become overcommitment. A clean 'no' given early is kinder than a broken 'yes' delivered late." },
    { emoji: "🎭", title: "Explore who you are alone", desc: "You define yourself through relationships. Spend time in solitude discovering what you think and feel without an audience." },
    { emoji: "🔍", title: "Develop your critical eye", desc: "Your Ti is tertiary — practice analyzing arguments without emotion. Not every idea deserves to be championed." },
    { emoji: "🌱", title: "Let people make their own mistakes", desc: "Your impulse to guide is loving, but growth sometimes requires failure. Hold space without intervening." },
    { emoji: "💤", title: "Rest is not laziness", desc: "Your energy is finite. Deep recovery — real rest, not just distraction — makes your leadership sustainable." },
  ],
  ENFP: [
    { emoji: "🎯", title: "Choose one thing", desc: "Your Ne generates 10 ideas a day. Pick the one that matters most and give it your full, undivided attention for 30 days." },
    { emoji: "📅", title: "Build a morning anchor", desc: "A consistent first hour creates a platform for your spontaneous energy. Try the same three things every morning." },
    { emoji: "📖", title: "Go deep on one topic", desc: "Your breadth is extraordinary. Practice depth — read everything on one subject for a month. It will change how you think." },
    { emoji: "🤐", title: "Finish conversations", desc: "You can leave people feeling dropped when your enthusiasm moves on. Consciously close the loops you open." },
    { emoji: "🌙", title: "Protect sleep", desc: "Your energy is your currency. Protect your sleep with the same ferocity you protect your freedom." },
    { emoji: "💪", title: "Do the boring part", desc: "The unsexy implementation is where your ideas live or die. Build the habit of doing the unglamorous work." },
  ],
  ISTJ: [
    { emoji: "🌱", title: "Embrace one new approach", desc: "Pick one area where you've always done things a certain way and try something different. Growth lives outside the procedure." },
    { emoji: "💬", title: "Express appreciation verbally", desc: "You show love through acts of service. Try putting it into words too — people need to hear it, not just experience it." },
    { emoji: "🎨", title: "Schedule unstructured time", desc: "Give yourself permission to do something with no outcome in mind. Not everything needs to be productive." },
    { emoji: "🧠", title: "Challenge your assumptions", desc: "Your Si holds experience as truth. Ask: 'Is this actually still true, or did it used to be true?' regularly." },
    { emoji: "🤝", title: "Ask for input more often", desc: "You prefer to work independently, but involving others in decisions often produces better results and stronger buy-in." },
    { emoji: "🌍", title: "Explore outside your comfort zone", desc: "Travel, new cuisine, unfamiliar perspectives — your Ne inferior hungers for novelty more than you realize." },
  ],
  ISFJ: [
    { emoji: "🗣️", title: "Speak your needs aloud", desc: "You are masterful at sensing others' needs. Practice stating your own clearly — it isn't selfish, it's necessary." },
    { emoji: "🚪", title: "Set one boundary this week", desc: "Choose something you've been tolerating and respectfully decline it. Your wellbeing matters as much as anyone else's." },
    { emoji: "🌱", title: "Experiment with change", desc: "Your Si values stability, but small experiments reduce the fear of change. Try one new thing a week, consequence-free." },
    { emoji: "✨", title: "Receive compliments graciously", desc: "When someone appreciates you, say 'thank you' without deflecting. You deserve the acknowledgment you give so freely." },
    { emoji: "📖", title: "Pursue a personal passion", desc: "Not everything you do needs to serve others. What do YOU love for its own sake? Do more of that." },
    { emoji: "🧘", title: "Process feelings before acting", desc: "When upset, pause before taking care of others. Your emotional state deserves attention and space." },
  ],
  ESTJ: [
    { emoji: "👂", title: "Slow down to listen", desc: "Your Te moves fast. Consciously slow the pace in conversations — you'll find more usable information in the gaps." },
    { emoji: "🎨", title: "Appreciate process, not just outcome", desc: "Practice enjoying the journey. Not everything valuable has an immediately measurable result." },
    { emoji: "💓", title: "Lead with curiosity", desc: "Before correcting, ask a question. Before directing, explore. You'll get further with people than with orders." },
    { emoji: "🌍", title: "Seek diverse perspectives", desc: "Your Si+Te can create echo chambers. Actively seek input from people whose background differs from yours." },
    { emoji: "🎭", title: "Let loose occasionally", desc: "Your Ne inferior craves fun and novelty. Give yourself permission to be spontaneous without a plan." },
    { emoji: "💝", title: "Verbalize appreciation", desc: "You show value through action. Also say it. People in your life need to hear that they matter to you." },
  ],
  ESFJ: [
    { emoji: "🪞", title: "Check your own opinion first", desc: "Before asking what others think, articulate your own view. Your Ti needs development — your opinion matters." },
    { emoji: "🚫", title: "Disagree out loud sometimes", desc: "Conflict feels threatening, but honest disagreement is the foundation of real trust. Try it in a low-stakes setting." },
    { emoji: "🎯", title: "Define success for yourself", desc: "You're skilled at meeting others' expectations. What does success look like on YOUR terms? Write it down." },
    { emoji: "🧘", title: "Detach from approval", desc: "Practice doing something you believe in even if no one validates it. Your worth doesn't live in others' opinions." },
    { emoji: "📚", title: "Develop a personal interest", desc: "Something just for you — not because it helps anyone else. Pursue it privately and with pleasure." },
    { emoji: "💤", title: "Rest without guilt", desc: "You give constantly. Rest is not abandonment — it is responsible stewardship of the energy you share." },
  ],
  ISTP: [
    { emoji: "💬", title: "Check in verbally", desc: "You show care through action. Also show it in words — tell people you appreciate them, even briefly." },
    { emoji: "🌱", title: "Commit to one long-term project", desc: "Your Se can pull you toward the next interesting thing. Plant a flag in something that requires months to complete." },
    { emoji: "🤝", title: "Ask for help occasionally", desc: "Your self-sufficiency is real, but letting others contribute builds the relationships your Fe inferior quietly wants." },
    { emoji: "📖", title: "Read about psychology", desc: "Understanding human motivation through a framework helps your Fe make sense of the emotional world." },
    { emoji: "🎭", title: "Express emotions deliberately", desc: "Pick one person you trust and, once a week, share something you're actually feeling — not just thinking." },
    { emoji: "🗓️", title: "Plan one future event", desc: "Your Ni inferior benefits from exercising foresight. Deliberately plan something six months out and build toward it." },
  ],
  ISFP: [
    { emoji: "🚀", title: "Share your art with the world", desc: "You create for yourself — which is beautiful. But sharing your work is an act of connection. Someone needs what you make." },
    { emoji: "📢", title: "Advocate for yourself", desc: "Your quiet nature means others often underestimate you. Speak up for your needs, ideas, and contributions." },
    { emoji: "📅", title: "Build gentle structure", desc: "A loose framework — not a rigid schedule — can protect your creative energy from being scattered." },
    { emoji: "🤔", title: "Think further ahead", desc: "Your Se lives in the present. Practice asking 'where do I want to be in 3 years?' and mapping a path there." },
    { emoji: "💬", title: "Express conflict directly", desc: "Withdrawing is your default. Practice naming what's bothering you to the person involved, calmly and simply." },
    { emoji: "🌐", title: "Connect with a creative community", desc: "ISFPs thrive among others who share aesthetic sensibility. Find your people — online or in person." },
  ],
  ESTP: [
    { emoji: "🔭", title: "Think three steps ahead", desc: "Your Ni inferior is your growth edge. Before acting, pause and ask: 'What happens if this goes exactly right — and wrong?'" },
    { emoji: "📖", title: "Read something demanding", desc: "Your Ti benefits from deep engagement with complex ideas. Pick a book that requires real intellectual effort." },
    { emoji: "💬", title: "Follow through on your word", desc: "Your spontaneous nature sometimes leads to abandoned commitments. When you say it, mean it — or don't say it." },
    { emoji: "🧘", title: "Sit with boredom", desc: "The impulse to escape discomfort is strong. Practice sitting still for 10 minutes daily. The insights surprise you." },
    { emoji: "💓", title: "Tend your close relationships", desc: "You're magnetic to many but deeply close to few. Invest deliberate time and attention in the people who matter most." },
    { emoji: "🎯", title: "Choose a long-range goal", desc: "Pick something that takes a year to achieve. Your ability to act fast is exceptional — learning to sustain it is transformative." },
  ],
  ESFP: [
    { emoji: "📋", title: "Build one real routine", desc: "A consistent morning or evening practice anchors your spontaneous energy and makes your best days more frequent." },
    { emoji: "💰", title: "Plan your finances", desc: "Your present-focus can underserve your future self. Spend 30 minutes setting up an automatic savings plan this week." },
    { emoji: "📖", title: "Read something complex", desc: "Push past the impulse to move on. A challenging book, a long documentary — sustained attention builds a more powerful mind." },
    { emoji: "🌙", title: "Create a wind-down ritual", desc: "Your Se is always switched on. A deliberate end-of-day ritual helps your nervous system genuinely recover." },
    { emoji: "💬", title: "Name difficult emotions", desc: "When something hurts, resist the urge to perform happiness. Naming what you feel is the first step to moving through it." },
    { emoji: "🤝", title: "Go deep with one person", desc: "Your warmth reaches many. Practice depth with one close friend — real vulnerability, not just good vibes." },
  ],
};

export const typeColors = {
  INTJ: { bg: "from-violet-900 via-violet-700 to-purple-600", badge: "bg-violet-100 text-violet-800", accent: "#7c3aed" },
  INTP: { bg: "from-cyan-900 via-cyan-700 to-blue-600", badge: "bg-cyan-100 text-cyan-800", accent: "#0891b2" },
  ENTJ: { bg: "from-amber-900 via-amber-700 to-red-600", badge: "bg-amber-100 text-amber-800", accent: "#d97706" },
  ENTP: { bg: "from-orange-800 via-orange-600 to-pink-600", badge: "bg-orange-100 text-orange-800", accent: "#ea580c" },
  INFJ: { bg: "from-emerald-900 via-emerald-700 to-teal-600", badge: "bg-emerald-100 text-emerald-800", accent: "#059669" },
  INFP: { bg: "from-green-900 via-green-700 to-emerald-600", badge: "bg-green-100 text-green-800", accent: "#16a34a" },
  ENFJ: { bg: "from-yellow-800 via-yellow-600 to-orange-500", badge: "bg-yellow-100 text-yellow-800", accent: "#ca8a04" },
  ENFP: { bg: "from-pink-900 via-pink-700 to-rose-600", badge: "bg-pink-100 text-pink-800", accent: "#db2777" },
  ISTJ: { bg: "from-slate-900 via-slate-700 to-blue-700", badge: "bg-slate-100 text-slate-800", accent: "#475569" },
  ISFJ: { bg: "from-sky-900 via-sky-700 to-indigo-600", badge: "bg-sky-100 text-sky-800", accent: "#0284c7" },
  ESTJ: { bg: "from-blue-900 via-blue-700 to-indigo-700", badge: "bg-blue-100 text-blue-800", accent: "#1d4ed8" },
  ESFJ: { bg: "from-teal-900 via-teal-700 to-cyan-600", badge: "bg-teal-100 text-teal-800", accent: "#0d9488" },
  ISTP: { bg: "from-gray-900 via-gray-700 to-zinc-700", badge: "bg-gray-100 text-gray-800", accent: "#4b5563" },
  ISFP: { bg: "from-rose-900 via-rose-700 to-fuchsia-600", badge: "bg-rose-100 text-rose-800", accent: "#e11d48" },
  ESTP: { bg: "from-red-900 via-red-700 to-orange-600", badge: "bg-red-100 text-red-800", accent: "#dc2626" },
  ESFP: { bg: "from-fuchsia-900 via-fuchsia-700 to-purple-600", badge: "bg-fuchsia-100 text-fuchsia-800", accent: "#a21caf" },
};